apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app
  namespace: default
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: capstone-app
    spec:
      containers:
      - image: amitnike/nginxhello:latest
        imagePullPolicy: Always
        name: capstone-app
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
              path: /
              port: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%